### ISSUE TITLE
Getting two errors when building the project (Help)

### ISSUE THREAD

**Issue by jegutierrez** [CapstoneLabs/slick#45]
Trying to build the project, I'm getting the following error in master:

```bash
./bot.go:142:11: bot.Slack.SetDebug undefined (type *slack.Client has no field or method SetDebug)
./updateable.go:29:105: cannot use u.newFormattedMessage() (type string) as type slack.MsgOption in argument to u.reply.bot.Slack.UpdateMessage
FAIL    github.com/jegutierrez/slick [build failed]
```

Am I doing something wrong? or is there another branch where this is not happening?

Thanks in advance,
Je

**Comment by mattouille** [comment]
I've seen this before when you don't use Go modules. Try setting `GO111MODULE=on`.

In your shell: `export GO111MODULE=on`

**Comment by jegutierrez** [comment]
Hey @mattouille I couldn't build the project 😢 (I'm getting the same error)
I'm running `make build` in the project root using `GO111MODULE=on`

**Comment by mattouille** [comment]
I noticed you're trying to build your fork. Have you tried cloning this repo and then building that?

**Comment by jegutierrez** [comment]
I get the same error just cloning the repo 👇 
<img width="781" alt="screen shot 2018-10-25 at 18 02 10" src="https://user-images.githubusercontent.com/4484320/47530164-31ef9b00-d880-11e8-8967-6c70a71c3714.png">

Looking at `slack.Client` it has no field or method SetDebug, as the error said,
also the `u.reply.bot.Slack.UpdateMessage` param is a `slack.MsgOption` not a string,
could it be that the app is broken in `master` branch?

**Comment by mattouille** [comment]
[`slack.Client`](https://github.com/nlopes/slack/blob/master/slack.go) belongs to nlopes/slack. It looks like you're right that they've removed the function.

I can understand why CI is passing, go.mod should be keeping it stuck to a certain tag or commit. Why is yours not doing the same?

**Comment by mattouille** [comment]
@jegutierrez I actually forgot to ask. What version of Go are you using?

**Comment by jegutierrez** [comment]
Hey @mattouille, here are the parts

go.mod:
```
github.com/nlopes/slack v0.4.0
```

go.sum:
```
github.com/nlopes/slack v0.4.0 h1:OVnHm7lv5gGT5gkcHsZAyw++oHVFihbjWbL3UceUpiA=
github.com/nlopes/slack v0.4.0/go.mod h1:jVI4BBK3lSktibKahxBF74txcK2vyvkza1z/+rRnVAM=
```

Any suggestion just let me know

**Comment by mattouille** [comment]
Those are exactly the same as mine. I think the usage of Go modules is being turned off for you somehow.

**Comment by thepudds** [comment]
Some quick comments. 

Sorry, not familiar with this project or build process (and on top of that, not quite following the problem), so hope these comments here don't inject confusion...

That said, you might want to check the output of `go list -m all` for the non-working environment, and compare that to `go list -m all` for a working environment.  That should show the actual versions being used, and perhaps that will highlight a difference.

(`go list -m all` is defined to show you the "build list", which is the actual versions that go into the build).

Is vendoring in play here? If so, might want to check that `go build -mod=vendor` is being used, or `GOFLAGS=-mod=vendor` is set or similar. (Modules by default ignore the `vendor` directory unless you tell them to look there).

One other thought is to double-check whether someone is using `GO111MODULE=on` environment variable vs. the plural `GO111MODULES=on`.  The first one without the `S` is correct, but people sometimes naturally include the `S` because the feature is often called "modules".

You can also double-check that `go env` shows a non-empty value for the read-only `GOMOD` variable `go env` should output. (If it is empty, it usually means modules are not actually enabled).

If running `go get` and it is failing in some surprising way, you can also check the output if you add `-v` or perhaps separately try with the even more verbose `-v -x` flags.

You could also double-check git versions. That was a problem especially during vgo and beta days, but less of a problem in 1.11 itself.

**Comment by mattouille** [comment]
I probably should include a vendor directory regardless. This would improve build times and keep pulls online even if other repos are messed up. That said, I still think it's odd that his setup seems to be ignoring Go modules. I say that because the Makefile is written in such a way that it reinforces the use of Go modules, unless the way that I've setup the Makefile is incorrect. I could imagine something in the environment overriding this, though I'm not sure what at this time.

**Comment by jegutierrez** [comment]
Hey @mattouille, @thepudds finally the project is building correctly 🤓 
Thanks for your patience and support 🙇 

The solution: 
First I was enabling the `GO111MODULE=on` before running the build or test,
But now I have added an env variable in my bash profile and is finally the error has disappeared.
However is still showing an empty `GOMOD=""` when running `go env` (but now is working)

I think we can close this issue,
Thank you very much!

**Comment by mattouille** [comment]
`GOMOD` is usually only populated when you're in a folder with go modules support, so maybe that answers that? Either way, I'm very glad you're building properly now!
